#!bin/bash
msg () {
local colors="new-adm-color"
if [[ ! -e $colors ]]; then
COLOR[0]='\033[1;37m' #BRAN='\033[1;37m'
COLOR[1]='\e[31m' #VERMELHO='\e[31m'
COLOR[2]='\e[32m' #VERDE='\e[32m'
COLOR[3]='\e[33m' #AMARELO='\e[33m'
COLOR[4]='\e[34m' #AZUL='\e[34m'
COLOR[5]='\e[35m' #MAGENTA='\e[35m'
COLOR[6]='\033[1;36m' #MAG='\033[1;36m'
COLOR[7]='\033[1;34m' #AZULR='\033[1;34m'
COLOR[8]='\e[0;31m' #rojoc='\e[0;31m'
else
local COL=0
for number in $(cat $colors); do
case $number in
1)COLOR[$COL]='\033[1;37m';;
2)COLOR[$COL]='\e[31m';;
3)COLOR[$COL]='\e[32m';;
4)COLOR[$COL]='\e[33m';;
5)COLOR[$COL]='\e[34m';;
6)COLOR[$COL]='\e[35m';;
7)COLOR[$COL]='\033[1;36m';;
8)COLOR[$COL]='\033[1;34m';;
9)COLOR[$COL]='\033[0;31m';;
esac
let COL++
done
fi
NEGRITO='\e[1m'
SEMCOR='\e[0m'
 case $1 in
  -ne)cor="${COLOR[1]}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}";;
  -ama)cor="${COLOR[3]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -verm)cor="${COLOR[3]}${NEGRITO}[!] ${COLOR[1]}" && echo -e "${cor}${2}${SEMCOR}";;
  -verm2)cor="${COLOR[1]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -azu)cor="${COLOR[6]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -verd)cor="${COLOR[2]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -bra)cor="${COLOR[0]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  "-bar2"|"-bar")cor="\e[1;34m▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\e[0m" && echo -e "${SEMCOR}${cor}${SEMCOR}";;
  -azuc)cor="${COLOR[7]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -rojoc)cor="${COLOR[8]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
esac
}



selection_fun () {
local selection="null"
local range
for((i=0; i<=$1; i++)); do range[$i]="$i "; done
while [[ ! $(echo ${range[*]}|grep -w "$selection") ]]; do
echo -ne "\033[1;33mSelecione una Opcion: \033[1;37m" >&2
read selection
tput cuu1 >&2 && tput dl1 >&2
done
echo $selection
}
clear
msg -bar
echo -e "BY JORGE BARBA" | lolcat -a -d 10
msg -bar
echo -ne "\033[1;31m[\033[1;37m1\033[1;31m] \033[1;33m > " && msg -azu "Español --> frances"
echo -ne "\033[1;31m[\033[1;37m2\033[1;31m] \033[1;33m > " && msg -azu "Español --> English"
echo -ne "\033[1;31m[\033[1;37m3\033[1;31m] \033[1;33m > " && msg -azu "English --> Español"
echo -ne "\033[1;31m[\033[1;37m4\033[1;31m] \033[1;33m > " && msg -azu "English --> Portugues"
echo -ne "\033[1;31m[\033[1;37m5\033[1;31m] \033[1;33m > " && msg -azu "Portugues --> English"
echo -ne "\033[1;31m[\033[1;37m0\033[1;31m] \033[1;33m > " && msg -bra "SALIR DEL SCRIPT"
msg -bar
selection=$(selection_fun 9)
case ${selection} in
0 | 00) echo -ne "\033[1;37mHASTA LUEGO" && exit ;;
1 | 01) python español_frances ;;
2 | 02) python español_ingles ;;
3 | 03) python ingles_español ;;
4 | 04) python ingles_portugues ;;
5 | 05) python portugues_ingles ;;
esac


msg -ne "Enter Para Continuar" && read enter
source traductor

